#!/bin/sh
#  ______
# |   __ \.-----.-----.--.--.--.--------.----.----.
# |   __ <|__ --|  _  |  |  |  |        |   _|  __|
# |______/|_____|   __|________|__|__|__|__| |____|
#               |__|

#pgrep -x sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a Xfce4-terminal state=floating
bspc rule -a feh state=floating

bspc config normal_border_color \#D38A0C 
bspc config active_border_color \#CCCCCC
bspc config focused_border_color \#D38A0C 
bspc config presel_feedback_color \#FFFFFF


feh --bg-scale $HOME/Pictures/deposito/yggdrasil1.jpg &
picom --experimental-backends &
setxkbmap -layout br &
bash $HOME/.config/polybar/launch.sh --shades &
sxhkd &
#Polkit
/usr/libexec/polkit-gnome-authentication-agent-1 &
# Adjusts the color temperature of screen
/usr/libexec/geoclue-2.0/demos/agent &
redshift-gtk &
copyq &
udiskie --smart-tray &
xautolock -time 10 -locker -corners **** lock 
#home/blx32/Pictures/deposito/yggdrasil1.jpg
